project:
  type: website

website:
  title: "IA-Introducere"
  page-navigation: true
  description: 'Curs de introducere în Inteligența artificială pentru elevi de liceu și studenți'
  search: true
  sidebar:
    style: "docked"
    background: "light"
    collapse-level: 3
    search: true
    contents:
      - text: "Prezentare curs"
        href: index.qmd
      - text: "Structură curs"
        href: structura-curs.qmd
        contents:
          - section: "Modul 1: Fundamentele Inteligenței Artificiale"
            contents:
              - text: "Structură modul 1"
                href: modul1/index.qmd
              - text: "---"
              - section: "1: Orientare către dezvoltarea competențelor IA"
                href: modul1/1_0.qmd
                contents:
                  - text: "Ce este IA?"
                    href: modul1/1_1.qmd
                  - text: "Istoria IA"
                    href: modul1/1_2.qmd
                  - text: 'Cum "învață" IA?'
                    href: modul1/1_3.qmd
                  - text: "Rolul tău"
                    href: modul1/1_4.qmd
      - text: "---"
      - section: "Altele"
        contents:
          - href: altele/licenta.qmd
            text: Licențe
          - href: altele/contact.qmd
            text: Contact

  page-footer:
    left: " Conținut {{< fa brands creative-commons >}} 2025 Cozmina Secula<br> Resursă sub licența [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/)."


format:
  html:
    theme: [cosmo, brand, style/style.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    include-in-header: "_include/header.html"
    toc: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5rem


