---
title: "Structura Curs"
---


::: {.grid}

::: {.g-col-12 .g-col-md-4}
::: {.card .h-100}
::: {.card-body}
<h3 class="card-title" style="color: #000000;">Modulul 1: Fundamentele IA</h3>
<p class="card-text">
Acest modul introduce participanții în lumea inteligenței artificiale. Vor explora exemple de tehnologie, vor învața despre algoritmi simpli și vor aprofunda principiile etice care stau la baza IA.
</p>
<br>
<div class="mt-3">
[date]{.badge .bg-light .text-dark} [algoritm]{.badge .bg-light .text-dark} [rezultat inteligent]{.badge .bg-light .text-dark} [controlul uman]{.badge .bg-light .text-dark} [supraveghere umană]{.badge .bg-light .text-dark} [principii etice și părtinire]{.badge .bg-light .text-dark} [scenarii din viața reală]{.badge .bg-light .text-dark} [discuții]{.badge .bg-light .text-dark} [lucru în grup]{.badge .bg-light .text-dark} [prezentări]{.badge .bg-light .text-dark} [feedback constructiv]{.badge .bg-light .text-dark}
</div>
:::
::: {.card-footer .bg-light}
[Vezi modulul &rarr;](modul1/index.qmd){.btn .btn-primary}
:::
:::
:::

::: {.g-col-12 .g-col-md-4}
::: {.card .h-100}
::: {.card-body}
<h3 class="card-title"style="color: #000000;">Modulul 2: IA Generativă</h3>
<p class="card-text">
<br>
În acest modul participanții utilizează instrumente IA generative pentru a crea imagini și text în timp ce lucrează în proiecte de grup. Participanții vor evalua critic caracteristicile IA utilizate de platformele digitale populare și vor înțelege scopurile și intențiile acestora folosind matricea etică a factorilor implicați.
</p>
<br>
<div class="mt-3">
[chatbot]{.badge .bg-light .text-dark} [IA generativă]{.badge .bg-light .text-dark} [generare de imagini]{.badge .bg-light .text-dark} [drepturi de autor și proprietate intelectuală]{.badge .bg-light .text-dark} [securitate și confidențialitate]{.badge .bg-light .text-dark} [conținut generat de IA]{.badge .bg-light .text-dark} [matricea etică a factorilor implicați]{.badge .bg-light .text-dark}
</div>
:::
::: {.card-footer .bg-light}
[În curând...]()
:::
:::
:::

::: {.g-col-12 .g-col-md-4}
::: {.card .h-100}
::: {.card-body}
<h3 class="card-title"style="color: #000000;">Modulul 3: Etica IA</h3>
<p class="card-text">
<br>
În cadrul celui de-al treilea modul, participanții își vor continua învățarea aplicând etica în analiza unei platforme populare de cumpărături. Vor explora fenomenul Deep Fakes, vor revizui și elabora politici publice pentru IA, dar și un robot pentru îngrijirea copiilor.
</p>
<br>
<div class="mt-3">
[Deep Fakes]{.badge .bg-light .text-dark} [proiectarea sistemelor IA]{.badge .bg-light .text-dark} [cetățenia IA]{.badge .bg-light .text-dark} [politici publice]{.badge .bg-light .text-dark} [implicații asupra mediului]{.badge .bg-light .text-dark} [proiectarea unui robot pentru îngrijirea copiilor]{.badge .bg-light .text-dark} [etica în design]{.badge .bg-light .text-dark}
</div>
:::
::: {.card-footer .bg-light}
[În curând...]()
:::
:::
:::

::: {.g-col-12 .g-col-md-4}
::: {.card .h-100}
::: {.card-body}
<h3 class="card-title"style="color: #000000;">Modulul 4: Proiectul final</h3>
<p class="card-text">
<br>
Modulul 4 încheie cursul cu o serie de sesiuni în care participanții lucrează la proiectul lor de grup, construind o experiență de învățare despre IA pentru comunitatea lor.
</p>
<br>
<div class="mt-3">
[brainstorming]{.badge .bg-light .text-dark} [lucru în echipă]{.badge .bg-light .text-dark} [planificare]{.badge .bg-light .text-dark} [design]{.badge .bg-light .text-dark} [feedback]{.badge .bg-light .text-dark} [prezentare]{.badge .bg-light .text-dark}
</div>
:::
::: {.card-footer .bg-light}
[Doar în format fizic]()
:::
:::
:::

:::