---
title: ""
format: html
---
# Licența Cursului

Acest curs, ca lucrare derivată, este publicat sub licența [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/).

Acest lucru înseamnă că sunteți liber(ă) să partajați și să adaptați materialele, cu condiția să oferiți atribuirea corespunzătoare și să distribuiți contribuțiile dumneavoastră sub aceeași licență.


# Atribuiri

Acest curs a fost dezvoltat prin adaptarea și utilizarea resurselor din următoarele surse. Atribuirile specifice și licențele originale sunt detaliate mai jos.


## Curriculum de Bază {#sec-curriculum}

Conținutul principal al acestui curs este o adaptare a curriculumului **[AI Generation](https://aigeneration.uipathfoundation.com/ro/)**, un proiect educațional creat de UiPath Foundation în parteneriat cu App Inventor Foundation și Global Science of Learning Education Network. Materialele originale sunt licențiate sub [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).

## Ilustrații {#sec-ilustratii}

Pe lângă materialele proprii, am folosit și adaptat ilustrații din sursele de mai jos. Versiunile modificate sunt, de asemenea, disponibile sub licența **CC BY-SA 4.0**.

| Nume ilustrație         | Autor(i)                           | Sursă / Licență                                                                                             |
|-------------------------|------------------------------------|-------------------------------------------------------------------------------------------------------------|
| [Artificial Intelligence V1](https://github.com/alan-turing-institute/turing-commons/blob/1159f36cdd15e035ea1ddd23d352ee29ad8039e3/docs/assets/images/illustrations/artificial-intelligence.png?raw=true) | Jonny Lighthands & Eléonore Guerra | [Turing Commons](https://alan-turing-institute.github.io/turing-commons/resources/gallery/) / [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) |
| [Citizen Engagement](https://github.com/alan-turing-institute/turing-commons/blob/main/docs/assets/images/illustrations/citizen-engagement.png?raw=true)     | Jonny Lighthands & Eléonore Guerra | [Turing Commons](https://alan-turing-institute.github.io/turing-commons/resources/gallery/) / [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) |
| [Participation](https://alan-turing-institute.github.io/turing-commons/resources/gallery/) | Jonny Lighthands & Eléonore Guerra| [Turing Commons](https://alan-turing-institute.github.io/turing-commons/resources/gallery/) / [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) |

## Videoclipuri {#sec-video}

Am folosit următoarele videoclipuri publicate sub licențe deschise.

| Nume videoclip       | Autor(i)           | Sursă / Licență                                                                                             |
|----------------------|--------------------|-------------------------------------------------------------------------------------------------------------|
| [Human agency and AI](https://www.youtube.com/watch?v=Hyq8j8SEx_Y) | Utrecht University | [YouTube](https://www.youtube.com/watch?v=Hyq8j8SEx_Y) / [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) |


## Alte materiale

<!-- Acest tabel poate fi completat dacă se folosesc și alte resurse, precum seturi de date, fragmente de cod etc. -->
| Resursă | Autor(i) | Sursă / Licență |
|---------|----------|-----------------|
|         |          |                 |

