on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Pre-install xfun and litedown
        run: |
          install.packages(c("xfun", "litedown", "renv"), repos = "https://cloud.r-project.org", lib = Sys.getenv("R_LIBS_USER"))
          .libPaths(Sys.getenv("R_LIBS_USER"))
          cat("xfun version: ", as.character(packageVersion("xfun")), "\n")
          cat("litedown version: ", as.character(packageVersion("litedown")), "\n")
          print(.libPaths())

      - name: Restore R packages (skip rebuild)
        run: |
          .libPaths(Sys.getenv("R_LIBS_USER"))
          renv::restore(rebuild = FALSE)
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
